
<?php
require('Views/header.phtml');

?>
<!-- Creates a chat box to display conversation between users -->
<div class="card text-dark bg-warning w-50 mx-auto" style="border-radius: 15px">
    <div class="card-header">
        <?php echo '<h1 class = "h4 mb-3 font-weight-normal">Chat with '.$_GET['username'].'</h1>'?>
    </div>
    <div class="card-body text-white bg-dark" style="overflow-y: scroll;height: 400px">
        <!-- Receiver Message-->
        <div class="row">
            <div class="col-sm" id="sentTo">
                <!-- Sender Message-->
            </div>
            <div class="col-sm" id="sentFrom">
            </div>
        </div>

    </div>
    <div class="card-footer bg-dark"style="border-bottom-left-radius: 15px;border-bottom-right-radius: 15px">
        <div class="input-group green-border-focus">
            <input type="text" placeholder="Type a message" aria-describedby="button-addon2" class="form-control rounded-1 border-0 py-4 bg-light" id="textArea">
            <div class="input-group-append">
                <button onclick="sendMsg(document.getElementById('textArea').value)" id="button-addon2" type="submit" class="btn btn-outline-success">Send</button>
            </div>
        </div>
    </div>
</div>
<br>
<br>


<script>
    let receiverName = '<?php echo $_GET['username']?>';
    let receiverId = '<?php echo $_GET['userid']?>';
    let Sender = '<?php echo $_SESSION['login']?>';

    getsent();
    getTo();

    setInterval(function(){ getTo();
    console.log("recieved")}, 3000);

    function getsent()
    {

        fetch(`fetchMessages.php?username=${receiverName}&userid=${receiverId}`).then(function(response)
        {
            return response.json();
        })

            .then(function (data)
            {


                document.getElementById('sentFrom').innerText = "";
                for(let i = 0; i < data.length; i++){
                    let element = "";
                    console.log(data[i].sender_id)
                    element = '<div style="border-radius: 15px" class="alert alert-primary"> <p style="font-size: 10px">'+data[i].post_time+'</p><p style="font-size: 14px">Sender: <b>'+Sender+'</b></p><hr><p>'+data[i].message+'<p></div>'


                    document.getElementById('sentFrom').innerHTML += element;
                }
            })

            .catch(function (error)
            {
                document.getElementById('contacts').innerText = 'Error: ' + error;
            })
    }

    function getTo()
    {

        fetch(`fetchMessages.php?username=${receiverName}&userid=${receiverId}&received=1`).then(function(response)
        {

            return response.json();
        })

            .then(function (data)
            {
                document.getElementById('sentTo').innerText = "";
                for(let i = 0; i < data.length; i++){
                    let element = "";
                    console.log(data[i].sender_id)
                    element = '<div style="border-radius: 15px" class="alert alert-success"> <p style="font-size: 10px">'+data[i].post_time+'</p><p style="font-size: 14px">Sender: <b>'+receiverName+'</b></p><hr><p>'+data[i].message+'<p></div>'

                    document.getElementById('sentTo').innerHTML += element;

                }



            })

            .catch(function (error)
            {
                document.getElementById('contacts').innerText = 'Error: ' + error;
            })
    }




    function sendMsg(message)
    {
        fetch(`fetchMessages.php?username=${receiverName}&userid=${receiverId}&insert=1&message="${message}"`).then(function(response)
        {
            document.getElementById('textArea').value= "";
            getsent();
            return response.json();
        })




    }

</script>

<?php
require ('Views/footer.phtml');
?>