<!-- Footer -->
<div
<br>
<br>
<br>
</div>
<div id="footerDiv"></div>
<footer class="footer">
    <div class="container">
        <span class="text-muted">© 2020 Copyright</span>
    </div>
</footer>
<!-- Footer -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/jquery-3.4.1.min.js"></script>
<script src="/js/bootstrap.min.js"></script>