<?php
require_once('Models/Users.php');
session_start();

$user = new Users();

if (isset($_GET['logout']) && $_GET['logout'] == true)
{
    $user ->logout();
}

?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Forum</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles -->
    <link href="/css/my-style.css" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Forum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/index.php">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/messages.php">Messages<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <?php if(!isset($_SESSION['login'])): ?>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/login.php">Login/Register</a>
            </li>
        </ul>

        <?php else: ?>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="?logout==true">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">My Profile</a>
            </li>
        </ul>
        <?php endif; ?>
    </div>
</nav>

</body>
</html>
